# ./buildspec.yaml

      version: 0.2

      phases:
        install:
          commands:
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
            - AWS_REGION=$AWS_DEFAULT_REGION
            - echo Installing NGINX
            - yum install nginx -y
        build:
          commands:
            - echo Build started on 'date'
            - cp index.html /var/www/html/
        post_build:
          commands:
            - echo Configuring NGINX

      artifacts:
        files:
          - /var/www/html/index.html
