apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eks
  template:
    metadata:
      labels:
        app: my-eks
    spec:
      containers:
        - name: my-eks
          image: AWS_ECR_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'